spring:
    main:
        banner-mode: "off"  # off/false = disable banner,default is true/on
    test:   
        async: "off"
        task: "on"
#customize properties spring.test.async
    output:
        ansi:
            enabled: DETECT


connection:
    username: admin
    remoteAddresses : 
      - 192.168.1.101
      - 192.168.1.102
#it we have serveral values use '-' (list,array)


logging: 
    pattern:
        console: '%-10relative  [%thread] %-5level %class{32}:%line -  %m%n' #relative is the number of milliseconds elapsed since the start of the program
#   file: 
#   path: 

#see base.xml => property:LOG_FILE =  ${LOG_FILE:-${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}}/spring.log} 



name: shijun


