spring:
    main: 
      banner-mode: "off"
 # off/false = disable banner,default is true/on

connection:
    username: admin
    remoteAddresses : 
      - 192.168.1.101
      - 192.168.1.102
#it we have serveral values use '-' (list,array)


name: shijun