spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF8&autoReconnect=true&useSSL=false
        username: root
        password: 19940120
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        properties:
            hibernate:
                show_sql: true
    test:
        cache: true
    cache:
        ehcache: #可以在此处设置查找ehcache配置文件的路径 see also CacheProperties
            config: classpath:cache/ehcache.xml
    redis:
        host: localhost
        port: 6379
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1